apiVersion: apps/v1
kind: Deployment
metadata:
  name: gee
  labels:
    app: gee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gee
  template:
    metadata:
      labels:
        app: gee
    spec:
      containers:
        - name: gee
          image: 127.0.0.1:5000/geeserver:v1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: "/opt/google/gehttpd/htdocs/cutter/globes/"
            name: nfsvol
          - mountPath: "/var/opt/google/pgsql/data/"
            name: nfsvol2
      volumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: nfsvol2
        persistentVolumeClaim:
          claimName: nfs-pvc2
---

apiVersion: v1
kind: Service
metadata:
  name: gee-service
spec:
  type: NodePort
  selector:
    app: gee
  ports:
  - protocol: TCP
    port: 8088
    nodePort: 30003
