apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    purpose: globe
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /share1
    server: 10.42.0.241
    readOnly: false
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
  labels:
    purpose: pgsql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /share2
    server: 10.42.0.241
    readOnly: false
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv3
  labels:
    purpose: password
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /share3
    server: 10.42.0.241
    readOnly: false
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv4
  labels:
    purpose: registry
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /share4
    server: 10.42.0.241
    readOnly: false
