apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
  selector:
    matchLabels:
      purpose: globes
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc2
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 10Gi
  selector:
    matchLabels:
      purpose: pgsql
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc3
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
  selector:
    matchLabels:
      purpose: password
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc4
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 15Gi
  selector:
    matchLabels:
      purpose: registry
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc5
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
  selector:
    matchLabels:
      purpose: gevol

